ns_checkout_homepage:
    path:     /
    defaults: 
        _controller: NSCheckoutBundle:Default:index

ns_checkout_exit:
    path:     /exit
    defaults: 
        _controller: NSCheckoutBundle:Default:exit

ns_checkout_ajax_remaining:
    path:     /remaining/{daystart}/{dayend}/{month}/{year}
    defaults: 
        _controller: NSCheckoutBundle:Ajax:remaining
    requirements:
        daystart: \d{1,2}
        dayend: \d{1,2}
        month:   \d{1,2}
        year:  \d{4}
        